src/Entity/Hobbies.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HobbiesRepository")
 */
class Hobbies
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->lien;
    }

    public function setLien(?string $lien): self
    {
        $this->lien = $lien;

        return $this;
    }
}

src/Entity/Projets.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjetsRepository")
 */
class Projets
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->lien;
    }

    public function setLien(?string $lien): self
    {
        $this->lien = $lien;

        return $this;
    }
}

src/Controller/PageAccueilController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Projets;
use App\Entity\Hobbies;
class PageAccueilController extends AbstractController
{
    /**
     * @Route("/page/accueil", name="page_accueil")
     */
    public function index()
    {
        $repository = $this->getDoctrine()-> getRepository(Projets::class);
        $projets = $repository->findAll();
        $repository = $this->getDoctrine()-> getRepository(Hobbies::class);
        $hobbies = $repository->findAll();

        return $this->render('page_accueil/index.html.twig', [
          'projets' => $projets ,
          'hobbies' => $hobbies 
        ]);
    }
    
    /**
     * @Route("/page/accueil/{id}", name="details")
     */
    public function details($id)
    {
        $repository = $this->getDoctrine()-> getRepository(Projets::class);
        $projets = $repository->find($id);

        return $this->render('page_accueil/details.html.twig', [
          'projets' => $projets 
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="stylesheet" href="https://bootswatch.com/4/superhero/bootstrap.min.css" > 
               
        {% block stylesheets %}
         {{ encore_entry_link_tags('appStyle') }}
        {% endblock %}
    </head>
    <body>

 <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <img class="rounded-circle  " src="http://videos.univ-nantes.fr/_imgs/medias/wvga/imgm5041.jpg" style="width:25%" alt="">
 <div class="content">
 <ul>
    <h1>MESSADI Radia</h1>
   <ul class="text-secondary"  > Adresse : Chez moi  :) </ul>
   <ul class="text-secondary" > Mail :  messadiradia@gmail.com</ul>
   <ul class="text-secondary" >Tel : 0006666688 </ul>
   <ul class="text-secondary" > RESEAUX PROFESSIONNELS </ul>
  <ul class="nav-item">
        <a class="text-primary" href="https://fr.linkedin.com"> linkedIn </a>
      </ul>
      <ul class="nav-item">
        <a class="text-primary" href=" https://github.com/radiaips"> Github  </a>
      </ul>
  </ul>    
</div>
 
</nav>
<div class="container">

        {% block body %}{% endblock %}
        {% block javascripts %}
        {% endblock %}
    </body>
</html>

templates/page_accueil/details.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<div >
<div class="col">
          <h1 class="text-center text-uppercase m-4">Descriptions de <small class="text-muted"> mes projets</small></h1>
    </ul>
<h1 class="text-info">{{projets.nom}} </h1>
    {{projets.description}}    
</ul>
<ul>
    <a href="{{projets.lien}}"> Cliquez ici pour en savoir plus sur le projet ^^!</a>
</ul>

</div>
{% endblock %}

templates/page_accueil/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello PageAccueilController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #808080; padding: 2px 6px; }
</style>
<section id="about" class="container content-section ">
<div>
    <h2>FORMATIONS</h2>
    <ul>
        <li> 2018-2020 : Master II Informatique pour les Sciences (IPS)</li>   
        <li>2016-2017 : Master II Architecture Villes et Territoires.</li>
        <li>2012-2015: Licence en architecture .</li>
        <li>2012-2013 : Diplôme technicienne en conception assistée par Ordinateur.</li>
    </ul>
</div>

<div>
    <h2>EXPERIENCES PROFESSIONNELLES </h2>
                
    <ul>
        <li>2017-2018 : Employée -Architecte-Bureau d’études techniques d'architecture et d’urbanisme.</li>
        <li>2014-2015 : Stagiaire -Bureau d’études d’architecture.</li>
        <li>2019 : Employée - Hôtesse Service client – Leroy Merlin</li>
    </ul>
</div>
<div>
<h2> PROJETS </h2>
{% for projets in projets %}
<ul>
<a href="{{path('details',{'id':projets.id})}}">{{projets.nom}}</a>
</ul>
{% endfor %}
</div>
<div>
<h2> ACTIVITES EXTRA-PROFESSIONNELLES </h2>
<ul>
{% for hobbies in hobbies %}
<ul>
{{hobbies.nom}}
</ul>
<ul>
    <a href="{{hobbies.lien}}"> Decouverte !</a>
</ul>
{% endfor %}
</ul>
</div>

</section>

{% endblock %}